updates in test, rm redundent from cat

diff --git a/.github/workflows/deploy_test.yml b/.github/workflows/deploy_test.yml
--- a/.github/workflows/deploy_test.yml
+++ b/.github/workflows/deploy_test.yml
@@ -48,6 +48,12 @@ jobs:
               echo "::error:: The gateway url status code wasn't 200. It was ${STATUS_CODE}"
               exit 1
           fi
+          RESPONSE=$(curl -X GET -s ${{ steps.apply.outputs.gate_url }})
+          RESPONSE_LOWER=echo "$RESPONSE" | sed 's/.*/\L&/'
+          if [[ "${RESPONSE}" == *"fact"* ]] && [[ "${RESPONSE_LOWER}" != *"error"* ]]; then
+              echo "::error:: The response wasn't what we expected. It was ${RESPONSE}"
+              exit 1
+          fi
 
       - name: 'Terraform Plan Destroy'
         uses: hashicorp/terraform-github-actions@master
